/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assign1;

import org.junit.Test;
import static org.junit.Assert.*;

public class ElectronicsTest {
    @Test public void testProductID() {
        Electronics p = new Electronics();
        p.setProductID("000000");
        assertEquals("ELectronicsTest's product ID should be 000000", "000000", p.getProductID());
    }

    @Test public void testDescription() {
        Electronics p = new Electronics();
        p.setDescription("Ipad");
        assertEquals("ElectronicsTest's Description should be Ipad", "Ipad", p.getDescription());
    }
    
    @Test public void testYear() {
        Electronics p = new Electronics();
        p.setYear(2020);
        assertEquals("ElectronicsTest's speed should be 2020", 2020, p.getYear());
    }

    @Test public void testPrice() {
        Electronics p = new Electronics();
        p.setPrice(10.0);
        assertTrue("ElectronicsTest's price should be $10", 10.0 == p.getPrice());
    }

    @Test public void testMaker(){
        Electronics testElectronics = new Electronics();
        testElectronics.setMaker("Apple");
        assertEquals("ElectronicsTest's price should be Apple", "Apple", testElectronics.getMaker());
    }
}
