/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assign1;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;

public class EStoreSearchTest {
    
    @Test public void testBookList() {
        ArrayList<Book> bookList= new ArrayList<Book>();
        Book b;
        try{
            b = new Book("000001", "Java Book", 10, 2020, "Affan Khan", "New York Times");
            bookList.add(b);
        }
        catch(Exception b1){
            System.out.println(b1.getMessage());
        }        
        assertTrue("BookTest's size should be 1", 1 == bookList.size());
    }

    @Test public void testElectronicsList() {
        ArrayList<Electronics> electronicsList= new ArrayList<Electronics>();
        Electronics e;
        try{
            e = new Electronics("000002", "ipad", 10, 2020, "Apple");
            electronicsList.add(e);
        }
        catch(Exception e1){
            System.out.println(e1.getMessage());
        }
        assertTrue("ElectronicsTest's size should be 1", 1 == electronicsList.size());
    }

    
    
}
